{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "332136a3",
   "metadata": {},
   "source": [
    "## Встроенные в Python исключения\n",
    "\n",
    "В Python встроено множество исключений, которые предупреждают о разных типах ошибок или ситуациях, возникающих во время выполнения программы.\n",
    "\n",
    "Вот некоторые исключения, с которыми вы можете столкнуться:\n",
    "\n",
    "* **ZeroDivisionError** — деление на ноль.\n",
    " * **ImportError** — проблемы с импортом модулей и пакетов.\n",
    " * **IndexError** — индекс последовательности находится вне допустимого диапазона.\n",
    " * **KeyError** — ключ словаря не найден в наборе существующих ключей.\n",
    " * **SyntaxError** — синтаксическая ошибка.\n",
    " * **TypeError** — операция применяется к объекту несоответствующего типа.\n",
    " * **ValueError** — функция получила аргумент правильного типа, но с недопустимым значением.\n",
    "\n",
    "Программисты могут не только использовать стандартные исключения, но и создавать собственные. Для этого нужно создать новый класс, унаследованный от встроенного класса `Exception`."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0a046f70",
   "metadata": {},
   "source": [
    "***\n",
    "## Как описать собственное исключение\n",
    "\n",
    "Чтобы описать собственное исключение, нужно создать новый класс, который наследуется от встроенного класса `Exception` или его подклассов. Подклассы — это конкретные исключения, например `SyntaxError`, `TypeError`, `IndexError`. Имя класса придумывает разработчик, но оно традиционно должно заканчиваться словом `Error`.\n",
    "\n",
    "При создании собственного исключения в качестве тела класса достаточно добавить докстринг:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea9a5305",
   "metadata": {},
   "outputs": [],
   "source": [
    "class FieldIndexError(IndexError):\n",
    "    \"\"\"Выбрасывается, если выбрано значение вне поля.\"\"\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8cca4f27",
   "metadata": {},
   "source": [
    "> Чтобы воспользоваться исключением, его необходимо «выбросить» в нужный момент. Для этого используется ключевое слово `raise`, за которым следует класс исключения, встроенного или пользовательского:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b95a4e7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# game.py\n",
    "\n",
    "from gameparts import Board\n",
    "# Из файла exceptions.py, который лежит в пакете gameparts,\n",
    "# импортируется класс FieldIndexError.\n",
    "from gameparts.exceptions import FieldIndexError\n",
    "\n",
    "def main():\n",
    "    game = Board()\n",
    "    game.display()\n",
    "    # Пользователь вводит номер строки.\n",
    "    row = int(input('Введите номер строки: '))\n",
    "    # Если введённое значение меньше нуля или больше или равно\n",
    "    # field_size (это значение равно трём, оно хранится в модуле\n",
    "    # parts.py)...\n",
    "    if row < 0 or row >= game.field_size:\n",
    "        # ...выбросить исключение FieldIndexError.\n",
    "        raise FieldIndexError\n",
    "    column = int(input('Введите номер столбца: '))\n",
    "    game.make_move(row, column, 'X')\n",
    "    print('Ход сделан!')\n",
    "    game.display()\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "afd7264c",
   "metadata": {},
   "source": [
    "В программе может быть задействовано много различных диапазонов и выбрасывание созданного исключения, скорее всего, будет востребованной операцией. Чтобы не дублировать каждый раз один и тот же текст исключения, его можно прописать в инициализаторе класса и при необходимости уточнять при выбрасывании исключения."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7330c585",
   "metadata": {},
   "outputs": [],
   "source": [
    "# gameparts/exceptions.py\n",
    "\n",
    "class FieldIndexError(IndexError):\n",
    "    \"\"\"Выбрасывается, если выбрано значение вне поля.\"\"\"\n",
    "    \n",
    "    def __init__(\n",
    "            self,\n",
    "            # Текст по умолчанию.\n",
    "            message='Введено значение за границами игрового поля!'  \n",
    "        ):\n",
    "        super().__init__(message)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a14e4b6d",
   "metadata": {},
   "source": [
    "***\n",
    "## «Укрощение» исключений в игре «Крестики-нолики»\n",
    "\n",
    "Чтобы обработать ситуацию, когда пользователь вводит некорректные координаты ячейки, вам понадобится бесконечный цикл `while`. Он будет работать до тех пор, пока пользователь не введёт корректные значения координат игрового поля. Как только нужные значения будут введены, цикл завершится, и программа продолжит свою работу."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c245409",
   "metadata": {},
   "outputs": [],
   "source": [
    "# game.py\n",
    "\n",
    "from gameparts import Board\n",
    "from gameparts.exceptions import FieldIndexError\n",
    "\n",
    "def main():\n",
    "    game = Board()\n",
    "    game.display()\n",
    "\n",
    "    # Запускается бесконечный цикл.\n",
    "    while True:\n",
    "        # В этом блоке содержатся операции, которые могут вызвать исключение.\n",
    "        try:\n",
    "            # Пользователь вводит значение номера строки.\n",
    "            row = int(input('Введите номер строки: '))\n",
    "            # Если введённое число меньше 0 или больше\n",
    "            # или равно game.field_size...\n",
    "            if row < 0 or row >= game.field_size:\n",
    "                # ...выбрасывается собственное исключение FieldIndexError.\n",
    "                raise FieldIndexError\n",
    "            column = int(input('Введите номер столбца: '))\n",
    "            # Если введённое число меньше 0 или больше\n",
    "            # или равно game.field_size...\n",
    "            if column < 0 or column >= game.field_size:\n",
    "                # ...выбрасывается собственное исключение FieldIndexError.\n",
    "                raise FieldIndexError\n",
    "        # Если возникает исключение FieldIndexError...\n",
    "        except FieldIndexError:\n",
    "            # ...выводятся сообщения...\n",
    "            print(\n",
    "                'Значение должно быть неотрицательным и меньше '\n",
    "                f'{game.field_size}.'\n",
    "            )\n",
    "            print('Пожалуйста, введите значения для строки и столбца заново.')\n",
    "            # ...и цикл начинает свою работу сначала,\n",
    "            # предоставляя пользователю ещё одну попытку ввести данные.\n",
    "            continue\n",
    "        # Если в блоке try исключения не возникло...\n",
    "        else:\n",
    "            # ...значит, введённые значения прошли все проверки\n",
    "            # и могут быть использованы в дальнейшем.\n",
    "            # Цикл прерывается.\n",
    "            break\n",
    "\n",
    "    game.make_move(row, column, 'X')\n",
    "    print('Ход сделан!')\n",
    "    game.display()\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "09c7592e",
   "metadata": {},
   "source": [
    "Блоки `try` и `except`:\n",
    "* Программа пытается выполнить операции в блоке `try`.\n",
    "* Если возникает исключение, управление передаётся блоку except."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "771fafe3",
   "metadata": {},
   "source": [
    "## Что в итоге\n",
    "\n",
    "* Исключения в Python — это события, которые возникают во время выполнения программы и сигнализируют о том, что что-то пошло не так, как ожидалось.\n",
    "* Чтобы описать собственное исключение, нужно создать новый класс, который наследуется от встроенного класса `Exception` или его подклассов.\n",
    "* Пример «укрощения» исключения:\n",
    "\n",
    "```Python\n",
    "try:\n",
    "    # Блок кода, который может вызвать исключение.\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError as e:\n",
    "    # Обработка исключения при делении на ноль.\n",
    "    print(f'Ошибка: {e}')\n",
    "else:\n",
    "    # Блок кода, который выполняется, если исключение не возникло.\n",
    "    print('Операция выполнена успешно.')\n",
    "finally:\n",
    "    # Блок кода, который выполняется всегда.\n",
    "    print('Программа завершила свою работу.')\n",
    "```"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
